spring:
  main:
    web-application-type: none
  sql:
    init:
      mode: never
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/coupon}
    username: ${DB_USERNAME:adminnn}
    password: ${DB_PASSWORD:adminnn}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 30000

  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: validate   # local: update / create, prod: validate
    properties:
      hibernate:
        default_schema: coupon
        format_sql: true
        jdbc:
          time_zone: UTC

  liquibase:
    enabled: true
    default-schema: coupon
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3

  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: false
minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  access-key: ${MINIO_ACCESSKEY:minioadmin}
  secret-key: ${MINIO_SECRETKEY:minioadmin123}
  bucketName: coupon
