server.port: 8500
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/coupon}
    username: ${DB_USERNAME:adminnn}
    password: ${DB_PASSWORD:adminnn}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 30000

  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update   # local: update / create, prod: validate
    properties:
      hibernate:
        default_schema: coupon
        format_sql: true
        jdbc:
          time_zone: UTC

  sql:
    init:
      mode: never



minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  access-key: ${MINIO_ACCESSKEY:minioadmin}
  secret-key: ${MINIO_SECRETKEY:minioadmin123}
  bucketName: coupon
