server.port: 8500
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/coupon}
    username: ${DB_USERNAME:adminnn}
    password: ${DB_PASSWORD:adminnn}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 30000

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update   # local: update / create, prod: validate
    properties:
      hibernate:
        default_schema: coupon
        format_sql: false
        jdbc:
          time_zone: UTC

  sql:
    init:
      mode: never
  cache:
    type: redis
    redis:
      time-to-live: 600000   # 10 dakika (ms)
      cache-null-values: false
      use-key-prefix: true
      key-prefix: "coupon::"
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: 2000ms
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_ADRESS:localhost:29092}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3


minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  access-key: ${MINIO_ACCESSKEY:minioadmin}
  secret-key: ${MINIO_SECRETKEY:minioadmin123}
  bucketName: coupon
